### ISSUE TITLE
Urlencode resuptionToken

### ISSUE THREAD

**Issue by justinkelly** [miku/metha#23]
Firstly, thanks for the amazing project!!
- it's working 99% perfect to do full oai harvests

1 issue I have is that 1 of the OAI feeds includes un-escaped characters in the resumptionToken
- refer below for examples

Unescaped `+`  - this url doesn't work

```
https://rosetta.slv.vic.gov.au/oaiprovider/request?resumptionToken=20210901000000@20210926235959@Primo@oai_dc@AAAWxpABYAAALK+AAU&verb=ListRecords
```

Escaped  `+` - this url does work

```
https://rosetta.slv.vic.gov.au/oaiprovider/request?resumptionToken=20210901000000@20210926235959@Primo@oai_dc@AAAWxpABYAAALK%2BAAU&verb=ListRecords
```

Is there a way to escape the resumptionToken with metha ?
- or a config options 

Cheers

Justin Kelly

**Comment by justinkelly** [comment]
patch to fix this problem has been submitted in pull request #24

**Comment by miku** [comment]
Thanks for the report - and fix!
