### ISSUE TITLE
Question: Can metha auto harvest all formats/metadataPrefixes?

### ISSUE THREAD

**Issue by justinkelly** [miku/metha#27]
Hi All,

I'm looking to bulk harvest all records from a number of OAI hosts
 - and for each host i'm not sure of all the formats/metadataPrefixes they support

Question: Can metha auto harvest all records in all formats?

Thanks

Justin

**Comment by miku** [comment]
You can use the `-format` parameter to set the format/metadataPrefix to harvest. 

To show all available formats for an endpoint, you can use `metha-id`, e.g.

```shell
$ metha-id http://caltechconf.library.caltech.edu/cgi/oai2 2> /dev/null | jq -rc .formats[].metadataPrefix 
didl
mets
oai_bibl
oai_dc
rdf
uketd_dc
```

**Comment by justinkelly** [comment]
awesome - thanks for the update @miku greatly appreciated
