### ISSUE TITLE
Dependency Issue with Version 0.2.37

### ISSUE THREAD

**Issue by tobiasschweizer** [miku/metha#31]
Hi @miku,

It has been a while :-) We worked with version  metha_0.2.32_amd64.deb which worked nicely.

Today I tried version metha_0.2.37_amd64.deb but got a problem when running it:

> metha-sync -v
metha-sync: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by metha-sync)
metha-sync: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by metha-sync)

I installed it like this: `sudo dpkg -i metha_0.2.37_amd64.deb` on a Ubuntu 20.04.3 LTS with go version go1.13.8 linux/amd64.

To me this looks like a dynamically linked lib that is missing. Maybe related: https://community.tmpdir.org/t/problem-with-go-binary-portability-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-32-not-found/123

For now, I switched to metha_0.2.36_amd64.deb which works. So I assume it must be something related to https://github.com/miku/metha/releases/tag/v0.2.37 as the release message states: 
- built with Go 1.20.2
- updated deps

Let me know if I can be of any assistance.

Kind regards,

Tobias

**Comment by miku** [comment]
Hello again, hope to catch-up sometime!

I hope [0.2.28](https://github.com/miku/metha/releases/tag/v0.2.38) fixes the issue. By default, Go is dynamically linked which may cause the problem you've seen. I'll build any new release with `CGO_ENABLED=0` - so this problem should not return in the future.
